DM-47738: Implement deconvolved initialization
lsst/meas_extensions_scarlet pull request #104
Opened 2024-12-23 19:20 UTC by fred3m

2025-02-07 03:54 UTC, taranu requested changes
Nothing really major but many comments of various kinds.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +            # Deconvolution does not use input catalog
You mean will not? Because it still can if that config is true, right?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +        catalog: afwTable.SourceCatalog | None = None,
Add docstring for this new param.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +                model.data[:] *= footprintImage
So... what does this do? You multiply the image by the index of each footprint, yes? Once it's deconvolved, what does that help with? Maybe add a short comment explaining here.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +# The name of the band in an monochome blend.
a monochromatic. But also, would it be wrong to assign a monochromatic blend a band? Even if it's a multi-band coadd one could call it `u,g,r,i,z,y` or something, no?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +    bbox: scl.Box | None = None,
Add doc for parameter

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +        raise ValueError("Scarlet mode data is empty")
model data

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +    blends = extraxctMonochrmaticBlends(
extractMonochromaticBlends

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +def extraxctMonochrmaticBlends(
extractMonochromaticBlends

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +) -> dict[int, scl.Blend]:
Can this function be unit tested (or is it covered by tests for other functions)?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +    modelData:
Are these colons from previous type annotations? Delete if they're not needed.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +    observation = buildMonochromeObservation(
Why monochrome instead of monochromatic? It's being used as an adjective so use one or the other consistently (I'd prefer monochromatic because it's exclusively an adjective even if it's longer).

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +def createMonochromeWeightImage(blends: list[scl.Blend], observation: scl.Observation) -> scl.Image:
Also suggest monochromatic here.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +            # Note that this is the deconvolvd source model
deconvolved... is this guaranteed to be true or just true in practice when used in this module?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +def buildMonochromeObservation(
Monochromatic again. This function doesn't seem like it belongs in an `io` module.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +) -> scl.Observation:
Add docstring

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +        assert bbox is not None  # needed for typing
You can cast instead, although the assert seems reasonable (even if only strictly necessary inside the if block - does keeping it outside really solve the typing issue?)

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +        parents = catalog[catalog["parent"] == 0]
Is there a name for top-level parents? I assume the exclusion of parents that are themselves children is deliberate.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +def calculateFootprintCoverage(footprint: afwFootprint, maskImage: MaskX) -> np.floating:
Also another function that really doesn't seem to relate to I/O.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
>      """Calculate the fraction of pixels with no data in a Footprint
Shouldn't there be a newline here?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +                sourceRecord.setFootprint(heavy)
This change seems unnecessary - it looks like the same line at the end of both blocks.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +    mDeconvolved: afwImage.MultibandExposure,
Suggest at least `multiDeconvolved` for clarity. But if you're been using `mExposure` everywhere else, I suppose it's better to be consistent.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        An indexed image of the scarlet footprints so that the value
Maybe say 'a footprint image as returned by footprints_to_image'?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +    # We don't use the variance here because testing has shown that we get
Maybe cite the ticket number for these tests? I know it'll be in the merge commit but that's harder to look up later.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        min_area=9,
Should this value be an arg/configurable?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            footprintArray[y - ymin, x - xmin] = True
Wait, does this mean that the footprint dilation sometimes removes peaks from the area? Otherwise why would you need to do this?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        (observation - deconvolved mode convolved with difference image).
deconvolved model convolved with the difference kernel, no?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        mExposure: afwImage.MultibandExposure,
See the comment about mDeconvolved above.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        sources :
Should be catalog

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
>              "Typically this is `1e-2` if measurements will be made on the "
Does this need updating?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                   "and will be removed in v29.0",
I think all of these should say after v29 - you definitely can't remove it as part of the v29.0 release. Also if v29 releases within eight weeks you'll have to wait longer.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
>          "This prevents sources from growing unrealistically outside "
Does the default of 1.0 actually do anything now? I'm a bit confused.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        # default=600,
I assume you will be removing these old commented defaults?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        deconvovled footprints, which have an intermediate
deconvolved

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                f"Using CI catalog limits, the original number of sources to deblend was {len(catalog)}.",
Why did you change this to an f-string? log calls shouldn't use them.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            f"Deblending {len(catalog)} sources in {len(mExposure)} exposure bands",
Same as above, this should not be an f-string.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        # using the deconovlved footprints.
deconvolved

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            f"{np.sum((catalog[self.deblendDepthKey] == 1) & (catalog[self.nPeaksKey] > 1))} "
no f-string

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                f"Deblended {index} PSF parents out of {nPsfBlendedParents} PSF parents"
no f-string

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                self.log.trace(f"Deblending parent {psfParent.getId()} directly")
no f-string

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    f"Split parent {psfParent.getId()} into {len(children)} deconvolved parents"
no f-string

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    psfParentModel.insert(blendModel)
Does this need to be done even if blendModel is None?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                psfParentModel = scl.Image(
I'm confused as to what psfParent means here. convolvedParent?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    nChild=np.sum([child[self.nChildKey] for child in deconvolvedParents]),
It seems like it would be better to iterate over the parents once and increment these values, although I suppose it would take more lines to initialize the values to zero.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                del child
Is this to reclaim the memory or to clear the record or both?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            f"Deblender results: {nPsfBlendedParents} parent sources were "
no f-string

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        for parentId in parentIds[1:]:
Seems like it would be safer to explicitly exclude `parent == 0`, even if we're not supposed to have negative ids.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            raise RuntimeError("Skipped parents should be handled when building the parent hierachy")
hierarchy. Should this be a RuntimeError or something more specific, or an assert - when is this expected to happen?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        self.log.trace(f"Parent {blendRecord.getId()}: deblending {len(peaks)} peaks")
no f-string

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                traceback.print_exc()
You can do `traceback.print_exception(type(e), e, e.__traceback__)`, though I don't know exactly what difference that makes.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                logMessage=f"Unable to deblend source {blendRecord.getId}: {blendError}",
Passing a string is also going to subvert deferred logging, whether or not it's an f-string.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        blendFootprintImage = blendModel.data > 0
The `convolve=False` above suggests this is the deconvolved model, or has it already been convolved with the difference kernel? In that case are any of the models strictly positive?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
>          skip: `bool`
Probably should remove this type

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        so we add records for all of the deblended children and deconvovled
deconvolved

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            # Since we use the first peak for the parent object, we should
Hmm, so right now what are parent flag like values `merge_peak_sky` set from? The first peak? Is that the "brightest" peak (across which band(s)) or...?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    continue
This could be `else:`, although I'm not sure if it matters.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            except:  # noqa: E722
What is being caught here? OutOfRange?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        peak :
Should be src

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        catalog :
This param seems to have been removed. Do you not have numpydoc linting? I recommend adding a pre-commit yaml with numpydoc-validation.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        # This key is not that useful anymore since we now keep track of
Seems like it should be deprecated then.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        area = np.sum(scarletSource.get_model().data > 0)
I know I saw this before but why are even zero-valued pixels excluded from the reduced chi squared?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +from scipy.signal import convolve
Wait, why are you using scipy convolve? I thought you had an fft convolve that was considerably faster. Last time I checked the direct convolution performance was less than ideal too.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +def afwFootprintToScarlet(footprint: afwFootprint, copyPeaks: bool = True):
This file is also starting to get a bit smelly with how many different things are in it. Why not put this in `footprints.py`?

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +def scarletFootprintToAfw(footprint: scl.detect.Footprint, copyPeaks: bool = True) -> afwFootprint:
Why isn't this just a member function of `scl.detect.Footprint`? You could also implement a `fromAfwFootprint` class method.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +def getFootprintIntersection(
It would also be nice to see this migrated to the `continueClass` for `afwFootprint`.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +        peaks from `footprint`, and 'right' copies the peaks from
footprint1

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +    if copyMethod is not None and copyMethod not in ['left', 'right']:
You could make it a `copyFromFirst` with `False` meaning copy from the second and `None` meaning don't copy at all, although I'm not sure if that's more intuitive. Left and right is slightly confusing with the names being 1 and 2, though.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +        if copyMethod == 'left':
I like `peaks = (footprint1 if copyMethod == 'left' else footprint2).peaks`, but your taste may vary.

2025-02-07 03:54 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +    """Convolve a multi-band images with the PSF in each band.
I think you need to comment this a bit more clearly that it's expecting a ndarray of particular dimensions and check that psfs is the same length (I suggest zip with `strict=True` for this purpose).

2025-02-07 03:54 UTC, taranu commented on tests/test_deblend.py
> +                        assert imageForRedistribution is not None
Can imageForRedistribution get modified between when you assign it above and here? If not, it seems pointless to assert something you define to always be True.

2025-02-07 21:59 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +                model.data[:] *= footprintImage
Sure, I'll add a comment. This basically uses the already detected footprints to mask the deconvolved image. This prevents the noise from allowing deconvolved footprints to sometimes contain flux outside of the convolved footprints. In theory it should never happen but in practice it can on occasion.

2025-02-07 22:00 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +            # Deconvolution does not use input catalog
Yes, I'll clarify the comment.

2025-02-07 22:01 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +# The name of the band in an monochome blend.
Yes, there is no harm in using the actual band, it would just be one extra parameter to pass around to a class that will be garbage collected once updateCatalogFootprint has finished running.

2025-02-07 22:03 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +    blends = extraxctMonochrmaticBlends(
😱

2025-02-07 22:05 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +) -> dict[int, scl.Blend]:
Right now it's tested in `test_deblend_task` by testing updateCatalogFootprints. At some point I should probably include some more atomic unit tests though,.

2025-02-07 22:07 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +    observation = buildMonochromeObservation(
Agreed, not sure why I didn't back then but I'll change accordingly.

2025-02-07 22:10 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +            # Note that this is the deconvolvd source model
Guaranteed to be true. `source.get_model` is always deconvolved, then the entire blend model is convolved together (if desired).

2025-02-07 22:12 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +def buildMonochromeObservation(
It's only used for IO with our monochromatic catalogs though. I guess I could put it in utils, but since it is only used in io.py I think it makes sense to keep it here.

2025-02-07 22:15 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +        parents = catalog[catalog["parent"] == 0]
Not really. Top-level, root, or depth = 0 all work for me.
The intermediate parents are intentionally excluded because they are (by definition) contained within the parent footprints.

2025-02-07 22:17 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +def calculateFootprintCoverage(footprint: afwFootprint, maskImage: MaskX) -> np.floating:
I guess I could rename the module `persistence` or something else, because these are all methods used to persist the scarlet lite models into footprints in our catalog. Technically all of the I/O is handled in scarlet lite and this is just the module that unpacks them.

2025-02-07 22:19 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +    mDeconvolved: afwImage.MultibandExposure,
Yes, here and in other modules I use `mExposure` for a `MultibandExposure`.

2025-02-07 22:22 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            footprintArray[y - ymin, x - xmin] = True
No. Sometimes faint sources do not have any flux above the threshold in the deconvolved image. But the sources were detected in the measurement catalog so we ensure that there is at least one non-zero pixel at their center (ie they are PSF sources).

2025-02-07 22:24 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                   "and will be removed in v29.0",
I mean, if that is the policy then I guess so. But it hasn't served any functionality for over a year so removing it sooner rather than later (before the first DR) would be better I think.

2025-02-07 22:26 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
>          "This prevents sources from growing unrealistically outside "
Yes. This is what sets the sparsity threshold to 1 * noise RMS (in the deconvolved frame). So any flux below that is truncated. At 25% noise RMS the sources still grow too much into the noise.

2025-02-07 22:27 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                f"Using CI catalog limits, the original number of sources to deblend was {len(catalog)}.",
Why not? I changed it to make it consistent with the rest of the strings in the package.

2025-02-07 22:30 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    psfParentModel.insert(blendModel)
There is no model to insert if it is none. I get your point though, if one of the intermediate blends fails we should probably at least flag the parent that there were failures.

2025-02-07 22:31 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                psfParentModel = scl.Image(
In my head it makes sense. It's a footprint convolved with the PSF, as opposed to a deconvolvedParent, which are the intermediate footprints. I'm open to renaming suggestions.

2025-02-07 22:34 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    nChild=np.sum([child[self.nChildKey] for child in deconvolvedParents]),
I'm not sure what you mean. It only runs one for each parent, which seems easier than keeping running totals. Or did I misunderstand your comment?

2025-02-07 22:35 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                f"Using CI catalog limits, the original number of sources to deblend was {len(catalog)}.",
It's the [first rule about logging](https://developer.lsst.io/stack/logging.html#basic-usage-in-python) in the dev guide. f-strings break deferred evaluation of log messages, and normally @timj yells at anyone who uses them. Having said that, the language in the dev guide isn't as clear as saying you MUST NOT ever use them.

2025-02-07 22:36 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                del child
This is to clear the record, otherwise there are dangling records for sources that were never actually deblended. That results in NaNs in the measurement catalog, which causes errors further down the pipeline (I found that out the hard way).

2025-02-07 22:39 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        blendFootprintImage = blendModel.data > 0
Yes, this is the deconvolved model, therefor strictly positive.

2025-02-07 22:40 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            # Since we use the first peak for the parent object, we should
It's the same exact code in the current version (including the comment). The idea is that the first (brightest) peak is the one assigned to the parent, so that is the one that sets the columns in the catalog.

2025-02-07 22:47 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        area = np.sum(scarletSource.get_model().data > 0)
This is restricting them the the deconvovled Footprint.

2025-02-07 22:50 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +from scipy.signal import convolve
scipy convovle has an fft implementation and that's what I use. I do have a faster implementation but only for repeated uses of the same kernel. The scarlet FFT class caches the FFT indices so that they don't have to be recalculated each time, but for just a one off (which is what the `multiband_convolve` helper function is) the cost of building the FFT object is more expensive.

2025-02-07 22:51 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +def afwFootprintToScarlet(footprint: afwFootprint, copyPeaks: bool = True):
That makes sense.

2025-02-07 22:53 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +def scarletFootprintToAfw(footprint: scl.detect.Footprint, copyPeaks: bool = True) -> afwFootprint:
Because scarlet lite does not depend on afw. I guess I could use a continue class, but then scl.detect.Footprint in the science pipelines would have different methods than the scl version, and I'm not too keen on doing that.

2025-02-13 21:24 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +        assert bbox is not None  # needed for typing
Yes. It's silly but just an artifact of the way that python does type checking. Other null-aware languages that I'm familiar with don't have this issue.

2025-02-13 21:27 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +                sourceRecord.setFootprint(heavy)
Yeah, I'm not sure what happened here. Maybe I was testing something at some point... ¯\_(ツ)_/¯

2025-02-13 22:09 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    psfParentModel.insert(blendModel)
I added a `deblend_childFailed` key that is set for parents with a least one child blend that fails.

2025-02-13 22:15 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            raise RuntimeError("Skipped parents should be handled when building the parent hierachy")
It should never happen. So an assert is fine, I just prefer RuntimeError.

2025-02-13 22:21 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                traceback.print_exc()
I think my version is the canonical way if you want to print the traceback for the current exception.

2025-02-13 22:22 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                logMessage=f"Unable to deblend source {blendRecord.getId}: {blendError}",
It seems worth it in this case to ensure that skipped sources are always logged, right?

2025-02-13 22:25 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    continue
Yeah, the block is long enough that I didn't see the need to put it in an `else` clause.

2025-02-13 22:29 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +                model.data[:] *= footprintImage
Ok, so you're using the footprintImage as a mask, basically, and not bothering to multiply by `(footprintImage > 0)` instead? That's fine I suppose, but maybe add a comment to that effect.

2025-02-13 22:34 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            footprintArray[y - ymin, x - xmin] = True
Hmm. It seems odd that a deconvolved source would not be above-threshold - even if it's spurious - unless you're setting a higher threshold than in the original detection, in which case I suppose it makes sense.

2025-02-13 22:38 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                   "and will be removed in v29.0",
I'm pretty sure we're planning to have v29 well before then, but either way yes, we can't remove code in the same major version it was deprecated in.

2025-02-13 22:41 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                psfParentModel = scl.Image(
`convolvedParentModel` seems clearer to me, then.

2025-02-13 22:43 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            except:  # noqa: E722
Yes. If a peak isn't actually contained in the footprint then we just skip it.

2025-02-13 22:45 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    nChild=np.sum([child[self.nChildKey] for child in deconvolvedParents]),
I mean you have N `[child[key] for child in deconvolvedParents]` list comprehensions instead of just one loop. If iterating over children is inexpensive then fine, it doesn't really matter.

2025-02-13 22:46 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                del child
Maybe worth leaving a comment about that for your future self, then.

2025-02-13 22:48 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        # This key is not that useful anymore since we now keep track of
Do you know the procedure for deprecating a column? I don't see that in the dev guide.

2025-02-13 22:56 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                traceback.print_exc()
After reading the traceback docs, I am now confused and indifferent, so carry on.

2025-02-13 22:58 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                logMessage=f"Unable to deblend source {blendRecord.getId}: {blendError}",
You're already passing in `blendRecord` so pre-formatting the message seems unnecessary; just pass `blendError` instead.

2025-02-13 23:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            except:  # noqa: E722
Ok, but then why bare except instead of a specific exception?

2025-02-13 23:11 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        area = np.sum(scarletSource.get_model().data > 0)
The next line seems to sum up chi^2 over the whole bbox, though. Are the entries zero outside of the deconvolved footprint?

I'm also somewhat confused as to why you'd want to compute chi^2 over the deconvolved footprint, although I grant that partitioning variance in a blend is arbitrary anyway, so maybe the details aren't important.

2025-02-13 23:18 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +def getFootprintIntersection(
Created DM-48947 to migrate to afw.

2025-02-13 23:20 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +from scipy.signal import convolve
Ok, well if you end up finding that you're spending a bunch of time on direct convolution, let me know and I'll see if I can do something about it.

2025-02-13 23:27 UTC, fred3m commented on tests/test_deblend.py
> +                        assert imageForRedistribution is not None
This is for the sake of mypy because it isn't smart enough to know that imageForRedistribution cannot be none anymore.

2025-02-13 23:31 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            footprintArray[y - ymin, x - xmin] = True
Not really. The whole point of pre-deconvolving is to initialize the sources to be compact, so I use a fairly tight sparsity constraint in deconvolution. There's no harm in deconvolving faint things all the way down to the PSF for initialization.

2025-02-13 23:32 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +from scipy.signal import convolve
The plot I was thinking of is at the end of [this notebook](https://github.com/lsst-dm/modelling_research/blob/main/jupyternotebooks/convolution.ipynb), although it's a few years old. But yeah scipy.signal.convolve's direct convolution performed terribly then.

2025-02-13 23:35 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +def scarletFootprintToAfw(footprint: scl.detect.Footprint, copyPeaks: bool = True) -> afwFootprint:
A conditional import would solve that, I think. Maybe not for docstrings.

I guess my question is whether you expect users (or other developers) to want to use any of these functions. Most of these look to be internal and so perhaps the organization of the module isn't that important. These conversions seem more likely to be something that a user might implement themselves if they couldn't find (and IMO free functions are harder to discover than members).

2025-02-13 23:39 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                    nChild=np.sum([child[self.nChildKey] for child in deconvolvedParents]),
Oh, I see what you mean. That is actually the way that I originally did it but I thought that this was more straightforward. But actually I should just be able to use `np.sum(deconvolvedParents[self.deblendnChild])` etc. for these.

2025-02-13 23:40 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            footprintArray[y - ymin, x - xmin] = True
That's my point, though. Deconvolution makes things more compact and therefore should guarantee that any peak that was above-threshold in the original convolved detection should have at least one pixel/peak in the deconvolved image.

2025-02-13 23:42 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            raise RuntimeError("Skipped parents should be handled when building the parent hierachy")
Well, apparently `lsst.pex.exception.LogicError` exists, so I recommend that if this is unambiguously a logic error and not something that the user could potentially avoid.

2025-02-13 23:43 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                logMessage=f"Unable to deblend source {blendRecord.getId}: {blendError}",
_skipParent is called in a few other places too, and each one has a different log message.

2025-02-13 23:48 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        area = np.sum(scarletSource.get_model().data > 0)
Yes, outside of the deconvovled footprint all of the pixels are by definition zero. I don't remember the exact argument that Jim and I arrived on when we discussed this a few weeks ago, but I think the gist of it was that restricting our chi^2 to the center of the models gives us a better measure of the chi^2 for a source with minimal influence from its neighbors.

2025-02-13 23:49 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +from scipy.signal import convolve
I've found it to work fine, especially for a one off like the one in utils. It isn't actually used anywhere in the code, it's just a convenience function for downstream debugging.

2025-02-13 23:52 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +def scarletFootprintToAfw(footprint: scl.detect.Footprint, copyPeaks: bool = True) -> afwFootprint:
I take your point and it's a good one. But there shouldn't be any reason for someone to need these downstream. Either they care about catalog sources and footprints, in which case they'll use our catalogs, or they care about scarlet models, in which case they'll use the scarletModelData object that we cache. Switching between them should only be done in this package I think.

2025-02-13 23:58 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            footprintArray[y - ymin, x - xmin] = True
Based not only on this ticket but also my exploration of attempting to do detection on the deconvolved images, what seems to happen is that because the noise in our images is correlated it is difficult to distinguish faint sources from noise. Without the sparsity constraint sources can be considerably bigger because the noise can extend well beyond the actual size of each source. I'd rather have things more compact than less for initialization, so I set a high threshold to get rid of all the noise, which also results in losing the faintest sources. But again, those sources will never be much bigger than the model PSF anyway, so this should be a completely safe tradeoff.

2025-02-19 04:22 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                logMessage=f"Unable to deblend source {blendRecord.getId}: {blendError}",
Well yeah, that's the problem - `_checkSkipped` is evaluating log messages that might not get printed. Having said that, first off I just realized this should be `blendRecord.getId()` anyway (right now it's just printing out a function reference), and secondly, passing `x.getId()` as an arg wouldn't help because it'd get evaluated whether it's in an f-string or not. But anyway, `_skipParent` should take something like `logMessageFormat` and `logArgs`.

2025-06-28 00:03 UTC, taranu reviewed
See comments. It looks like a lot changed since the original review but I glossed over parts that looked more familiar.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +    observation :
Missing type

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +    signal_mask = observation.images.data > 3*noise_level
Why not just put `signal_pixels = np.sum(signal_mask)` here then?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +        doc="Background model to subtract from the cell-based coadd",
I didn't really follow the cell coadd changes, is this the pattern I need to follow for multiprofit too?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
>          Parameters
Missing docstrings for catalog/band. You may want to add a `pyproject.toml` with a `[tool.numpydoc_validation]` entry. It's a little annoying but ultimately helpful.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +
Missing doc for band.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +"""Functions for converting between afw and scarlet footprints."""
Missing the copyright boilerplate.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +    catalog:
Is your editor adding all of these colons?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def footprintsToNumpy(
FYI I've found this function useful and am thinking of putting it upstream. Maybe in `python/lsst/afw/table/_source.py` as `getFootprintArray`?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +        result[yidx, xidx] = 1
Consider an option - maybe `do_segmentation`? - to make it `result[yidx, xidx] = src.getId()` instead.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def getFootprintIntersection(
Isn't this something that could go in afw? It doesn't seem to use anything from scarlet.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def scarletModelToHeavy(
Does this need a sanity check that the source is actually part of the blend?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +    It seems like there should be a better way to do this but
It seems pretty straightforward to me, not sure what an easier alternative could be...

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +monochromaticBand = "dummy"
I notice you added a `'dummy'` kwarg default above, does it make sense to define this in one place and refer to it everywhere else?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +    catalog :
catalog & bbox seem to have been removed from the kwargs.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +def calculateFootprintCoverage(footprint: afwFootprint, maskImage: MaskX) -> np.floating:
I think you added `footprint.py` since then? That seems like a more logical place for this function.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +    blendFootprint:
docstring out of sync with kwargs again.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/io.py
> +        lite assumes that the PSF is the same for all bands.
This is the sigma=0.8 pix (circular integrated?) Gaussian intrinsic PSF, right?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +
missing doc for config.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +    residual :
This doesn't seem to exist anymore, or else I would ask why it needs to.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                   "This field will be removed in v29.0",
It's after v29... not sure what the timeline is supposed to be now.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        # Depending on the outcode of RFC-1076 the parent keys may be removed.
Well, what's happening with that RFC? I didn't follow it very closely.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            doc="deblend_nPeaks from this records parent.",
Hmm, is this really necessary? It may be convenient but then so would copying a lot of other parent values, whereas one should be able to look them up without concern over whether they're in sync.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +    ) -> tuple[afwTable.SourceCatalog, scl.io.ScarletModelData]:
Is this correct?

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            "split into %d deconvovled parents,"
deconvolved

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        parent :
not a kwarg anymore, nor is children

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        sclFootprint :
Seems to be a list now.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            except:  # noqa: E722
This doesn't seem to be resolved.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +    """Create a PSF image at the neareset valid location
nearest. This is only needed for deconvolution when the central pixel happens to be invalid, right? And I suppose this should be moot for cell-based coadds.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +def computeNearestMultiBandPsf(
Suggest `computeNearestPsfMultiBand` for autocomplete ease if nothing else.

2025-06-28 00:03 UTC, taranu commented on python/lsst/meas/extensions/scarlet/utils.py
> +    if incomplete:
This behaviour should be described in the docstring.

2025-06-28 00:03 UTC, taranu commented on tests/test_deblend.py
> +        # bigfoot = Footprint(ss)
So Bigfoot does exist... but probably shouldn't live in commented-out code.

2025-06-28 00:03 UTC, taranu commented on tests/test_deblend.py
> +                        source = [
You can use `next(src for ...)` for conditional generators.

2025-06-28 00:03 UTC, taranu commented on tests/test_deblend.py
> +        # implementation ticket (DM-47738).
Okay, but you should probably add a TODO then.

2025-07-01 14:27 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +        doc="Background model to subtract from the cell-based coadd",
I think so. Maybe ask @arunkannawadi . I just followed the pattern that he used in `pipe_tasks.deblendCoaddSourcesPipeline`.

2025-07-01 14:30 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +    catalog:
No. I do it out of habit because every other use of colons in python uses `statement:` instead of `statement :` and I personally hate that numpy docs couldn't stick to that standard. After more than a decade of not typing spaces before colons in python my muscle memory just doesn't do that.

2025-07-01 14:42 UTC, arunkannawadi commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +        doc="Background model to subtract from the cell-based coadd",
Yup, you'll need the background connection and subtract it on the fly if you will be using the cell-based coadds

2025-07-01 15:16 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +    observation :
Parameter types are not needed in docstrings when using type hints (but for some reason return types are).

2025-07-01 15:24 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def footprintsToNumpy(
Good idea. I created DM-51668 for this, with some suggestions for improvement.

2025-07-01 15:29 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +        result[yidx, xidx] = 1
I like this suggestion. I added an `asBool` parameter and update line 52 as you requested. If `isBool` is true then before returning the result it sets `result = result != 0`.

2025-07-01 15:32 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def scarletModelToHeavy(
It checks for the overlap between the sources bounding box and the blend, which should be sufficient.

2025-07-01 15:35 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def getFootprintIntersection(
It could, but I'd rather that be done in a different ticket.

2025-07-01 15:38 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +    It seems like there should be a better way to do this but
The comment is because I think that there should be a way to create a peak catalog without having to go through a footprint as an intermediary. But AFAICT there is no way to create a peak catalog outside of a footprint.

2025-07-01 15:41 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +monochromaticBand = "dummy"
I don't think that's necessary. It's only used internally and can be anything, as it doesn't make its way into anything returned by any of the code in the repo. But it does have to be consistent internally, which is why I added it to the module scope.

2025-07-01 15:51 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +        lite assumes that the PSF is the same for all bands.
Yes, that is the default for the science pipelines but it is a free parameter in ScarletDeblendTask.

2025-07-01 15:54 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +                   "This field will be removed in v29.0",
Yeah, I'll have to update all of these to v30 now. :(

2025-07-01 16:13 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +        # Depending on the outcode of RFC-1076 the parent keys may be removed.
Jim wants some testing to see
1. If it is possible to remove the parents in the source catalogs. This is because while working on this ticket I found that there are a lot of assumptions made in measurement and one might be that all sources have a parent in the catalog. If so then we have to keep the parents here, and there _are_ assumptions that all sources have measurements of ra and dec.
2. We need to test to see if there is any utility in making measurements on parents.

In the meantime we did decide to create a separate catalog for the intermediate parents (hence all of the refactors in this ticket since your first review). I did create DM-51670 to remove the parent columns from `object_deblend` but I cannot do it now because the analysis_tools metrics depend on those columns being present and I don't think that it should hold up getting the features of this ticket into place.

2025-07-01 16:15 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            doc="deblend_nPeaks from this records parent.",
This is needed because the footprints are not in the object tables. So if people want to know things like "did this come from a blend, and if so how big was the blend" they need this column (and it is persisted to the object tables).

2025-07-01 16:16 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +    ) -> tuple[afwTable.SourceCatalog, scl.io.ScarletModelData]:
Fixed it.

2025-07-01 16:16 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            "split into %d deconvovled parents,"
I don't know why my fingers always transpose the "l" and the "v"...

2025-07-01 16:22 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/utils.py
> +    """Create a PSF image at the neareset valid location
Yes. So when we switch to only cell-based coadds this shouldn't be necessary anymore.

2025-07-01 17:36 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/io.py
> +def calculateFootprintCoverage(footprint: afwFootprint, maskImage: MaskX) -> np.floating:
I don't think so because this is only used in io to update the SourceCatalog.

2025-07-01 19:57 UTC, taranu commented on python/lsst/meas/extensions/scarlet/deconvolveExposureTask.py
> +    observation :
Oh, I thought you meant to include them. I'd just drop the colons entirely then, though I suppose if the formatter doesn't care then fine.

2025-07-01 19:59 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def getFootprintIntersection(
That's fine, but better to get that created and merged quickly after this ticket so nobody has time to get used to it being in this package only. Or just do it with the footprintsToNumpy ticket.

2025-07-01 20:00 UTC, taranu commented on python/lsst/meas/extensions/scarlet/footprint.py
> +    It seems like there should be a better way to do this but
Ok, I'd just say that then (that there should be a way to create a peak catalog without a footprint), only because I've made these kind of notes before and then forgotten what was supposed to be easy.

2025-07-01 20:13 UTC, taranu commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            doc="deblend_nPeaks from this records parent.",
Hmm. Would it make sense to add a `parents` table, separate from the `object_nonprimary` (and on another ticket)? Some of these per-blend detection/deblending columns seem useful to have in a non-afw table.

2025-07-01 20:29 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/footprint.py
> +def getFootprintIntersection(
Ok, I added it to that ticket.

2025-07-01 20:39 UTC, fred3m commented on python/lsst/meas/extensions/scarlet/scarletDeblendTask.py
> +            doc="deblend_nPeaks from this records parent.",
That makes sense. I think non-primary is currently parents | sky objects | outer tract | outer patch objects. I don't think that we need to persist sky objects (and maybe those aren't in there), and it would probably be better to create a parents table and outer regions table instead of having a single `non-primary` table that lumps them all together (assuming that RFC-1076 passes eventually).

2025-07-03 02:25 UTC, merged